### ISSUE TITLE
Can not understand the error

### ISSUE THREAD

**Issue by 18209018** [ldiao/MixMir#1]
I got error: 

```
Solving MLM with GEMMA
Parsing files for PLINK
Removing 4096 motifs with no information
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:68: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:2079: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:2087: RuntimeWarning: invalid value encountered in true_divide
  return (dot(X, X_T.conj())/fact).squeeze()
Traceback (most recent call last):
  File "MixMir.py", line 157, in <module>
    doAll(doKin=doKin)
  File "MixMir.py", line 18, in doAll
    runParse(doKin=doKin)
  File "MixMir.py", line 43, in runParse
    parseAll.doAll(doKin=doKin,seqf=seqf,exprf=exprf,outfnkin=kinf,outPedFile=outPedFile,outMapFile=outMapFile,kkin=kkin,kmotif=kmotif,frac=frac,useFast=useFast)
  File "/media/bharata/1TB_1/MixMir/parseAll.py", line 64, in doAll
    makeKin(dcounts=kin_dcounts,genes=genes,outfn=outfnkin,useFast=useFast) 
  File "/media/bharata/1TB_1/MixMir/parseAll.py", line 247, in makeKin
    np.savetxt(outfn,K,delimiter='\t',fmt='%.4f')
  File "/usr/local/lib/python2.7/dist-packages/numpy/lib/npyio.py", line 1116, in savetxt
    ncol = X.shape[1]
IndexError: tuple index out of range
```

I really don't understand why. My input is like this:

For mature.fa, I downloaded from the database.
For the UTR fasta, I already create a fasta according to the input format

```
>refGene_NM_001662 range=7:127591299-127591705  5'pad=0 3'pad=0 strand=+ repeatMasking=none
CCAGCCAGGGGCAGGCCCCTGATGCCCGGAAGCTCCTGCGTGCAT
```

For the gene expresion file, my file:

```
ENST00000616518     1.11843
ENST00000620773     0
ENST00000619103     0
ENST00000611520     1.11843
ENST00000390393     2.23687
ENST00000390394     4.47373
ENST00000542354     1.11843
```

**Comment by ldiao** [comment]
Hi, one problem might be that the gene names in your fasta file and gene expression files do not match--MixMir first parses both files and finds genes with expression information.

Best,
Liyang

**Comment by 18209018** [comment]
Thank you. I think I know the problem now. Also, in getInfo function in parseAll.py file, I think the code is too strict for finding the gene name. It always checks pattern with XrefGene_X_X. My format before was slightly different so I changed this code to become not too strict like that. For now, it works and I need to analyze the result. Currently,  I think your software is suitable for what my advisor wants to check. If there is any other thing I want to discuss, can I ask you? Thank you very much.

**Comment by ldiao** [comment]
Yes I agree, the parsing function is too strict, but to be honest when I wrote it it was pretty ad hoc :) Please feel free to contact me with any further questions, good luck!

Liyang
